
### CodeSystem: Organization type
GET http://localhost:3000/api/hl7/CodeSystem-organization-type

### CodeSystem: Location type
GET http://localhost:3000/api/hl7/CodeSystem-location-physical-type

### CodeSystem: ActCode
GET http://localhost:3000/api/hl7/CodeSystem-v3-ActCode

### CodeSystem: ParticipationType
GET http://localhost:3000/api/hl7/CodeSystem-v3-ParticipationType
