### CodeSystem-allergyintolerance-clinical
GET http://localhost:3000/api/hl7/CodeSystem-allergyintolerance-clinical

### CodeSystem-allergyintolerance-verification
GET http://localhost:3000/api/hl7/CodeSystem-allergyintolerance-verification

### CodeSystem-condition-category
GET http://localhost:3000/api/hl7/CodeSystem-condition-category

### CodeSystem-condition-clinical
GET http://localhost:3000/api/hl7/CodeSystem-condition-clinical

### CodeSystem-diagnosis-role
GET http://localhost:3000/api/hl7/CodeSystem-diagnosis-role

### CodeSystem-discharge-disposition
GET http://localhost:3000/api/hl7/CodeSystem-discharge-disposition

### CodeSystem-dose-rate-type
GET http://localhost:3000/api/hl7/CodeSystem-dose-rate-type

### CodeSystem-location-physical-type
GET http://localhost:3000/api/hl7/CodeSystem-location-physical-type

### CodeSystem-medicationrequest-category
GET http://localhost:3000/api/hl7/CodeSystem-medicationrequest-category

### CodeSystem-medicationrequest-course-of-therapy
GET http://localhost:3000/api/hl7/CodeSystem-medicationrequest-course-of-therapy

### CodeSystem-observation-category
GET http://localhost:3000/api/hl7/CodeSystem-observation-category

### CodeSystem-organization-type
GET http://localhost:3000/api/hl7/CodeSystem-organization-type

### CodeSystem-practitioner-role
GET http://localhost:3000/api/hl7/CodeSystem-practitioner-role

### CodeSystem-service-type
GET http://localhost:3000/api/hl7/CodeSystem-service-type

### CodeSystem-v2-0074
GET http://localhost:3000/api/hl7/CodeSystem-v2-0074

### CodeSystem-v2-0131
GET http://localhost:3000/api/hl7/CodeSystem-v2-0131

### CodeSystem-v2-0203
GET http://localhost:3000/api/hl7/CodeSystem-v2-0203

### CodeSystem-v2-0276
GET http://localhost:3000/api/hl7/CodeSystem-v2-0276

### CodeSystem-v2-0443
GET http://localhost:3000/api/hl7/CodeSystem-v2-0443

### CodeSystem-v3-ActCode
GET http://localhost:3000/api/hl7/CodeSystem-v3-ActCode

### CodeSystem-v3-MaritalStatus
GET http://localhost:3000/api/hl7/CodeSystem-v3-MaritalStatus

### CodeSystem-v3-ParticipationType
GET http://localhost:3000/api/hl7/CodeSystem-v3-ParticipationType

### CodeSystem-v3-RoleCode
GET http://localhost:3000/api/hl7/CodeSystem-v3-RoleCode

### CodeSystem-v3-orderableDrugForm
GET http://localhost:3000/api/hl7/CodeSystem-v3-orderableDrugForm
