@Org_id=
@Organization_id=

### Organization - Create
POST http://localhost:3000/api/satusehat/Organization
Content-type: application/json

{
    "active": true,
    "identifier.0.use": "official",
    "identifier.0.value": "Pos Imunisasi LUBUK BATANG",
    "type.0.coding.0.code": "dept",
    "type.0.coding.0.display": "Hospital Department",
    "name": "Pos Imunisasi",
    "partOf.reference": "Organization/{{Organization_id}}"
}

### Organization - By ID
GET http://localhost:3000/api/satusehat/Organization/:id

### Organization - Update
GET http://localhost:3000/api/satusehat/Organization/:id

### Organization - Search by Name
GET http://localhost:3000/api/satusehat/Organization?name=paramarta

### Organization - Search by PartOf
GET http://localhost:3000/api/satusehat/Organization?partof={{Organization_id}}

### Organization - Update
PUT http://localhost:3000/api/satusehat/Organization/:id
Content-type: application/json

{
    "id": "abddd50b-b22f-4d68-a1c3-d2c29a27698b",
    "active": false,
    "identifier.0.use": "official",
    "identifier.0.value": "R220001",
    "type.0.coding.0.code": "dept",
    "type.0.coding.0.display": "Hospital Department",
    "name": "Rawat Jalan Terpadu",
    "partOf.reference": "Organization/{{Organization_id}}"
}

### Organization - Patch
PATCH http://localhost:3000/api/satusehat/Organization/:id
Content-Type: application/json-patch+json

{
    "0.op": "replace",
    "0.path": "/name",
    "0.value": "RAJAL TERPADU"
}

